show tables;

-- 기업회원탈퇴목록
SELECT /* CUSTOM_KIND */
	DEL_PRAC.CUSTOM_ID CUSTOM_ID,
	DEL_PRAC.OVER_DAYS_USER_DEL OVER_DAYS_USER_DEL,
	IFNULL(DEL_OVER.OVER_FLG, 'PRAC') OVER_FLG, 
	DEL_PRAC.DELETE_DATE DELETE_DATE, 
	DEL_PRAC.DELETE_USER DELETE_USER 
FROM 
	(SELECT A.CUSTOM_ID, TIMESTAMPDIFF(DAY, A.DELETE_DATE, NOW()) AS OVER_DAYS_USER_DEL, A.DELETE_DATE, A.DELETE_USER     
	FROM CUSTOM_COMP_LOGIN A, CUSTOM_COMP B 
	WHERE A.DELETE_DATE IS NOT NULL -- 탈퇴회원(임시탈퇴자, 로그인삭제일) 
	AND A.CUSTOM_ID = B.CUSTOM_ID 
	) AS DEL_PRAC 
LEFT OUTER JOIN 
	(SELECT CUSTOM_ID, 'OVER' AS OVER_FLG 
	FROM CUSTOM_COMP_LOGIN 
	WHERE TIMESTAMPDIFF(DAY, DELETE_DATE, NOW()) >= 30 
	) AS DEL_OVER 
ON DEL_PRAC.CUSTOM_ID = DEL_OVER.CUSTOM_ID 
ORDER BY OVER_FLG ASC, OVER_DAYS_USER_DEL DESC;

UPDATE CUSTOM_COMP SET DELETE_DATE = DEFAULT, DELETE_USER = 'ADMIN' WHERE CUSTOM_ID = '';
UPDATE CUSTOM_PERSON SET DELETE_DATE = DEFAULT, DELETE_USER = 'ADMIN' WHERE CUSTOM_ID = '';

CREATE TABLE CUSTOM_COMP_HISTORY (
	SEQ				INT(15)		AUTO_INCREMENT UNIQUE KEY,
	CUSTOM_ID 		INT(8) 		NOT NULL PRIMARY KEY,
	CUSTOM_KIND_CD	INT(3) 		NOT NULL COMMENT '1:기업고객|2:개인고객|101:유통|102:대형마트|103:중형마트|104:소형마트|105:편의점|201:공장|202:택배|203:우체국|301:컨테이너위탁업체|302:트랙카위탁업체|303:표준위탁업체|501:항공운송|502:선박운송|503:기차운송|505:표준차량운송|506:고속버스운송|507:개별차량운송|601:농업공급자|602:수산업공급자|603:축산업공급자',
	CUSTOM_GRADE	VARCHAR(1) 	NOT NULL COMMENT 'A:우수기업고객|B:정규기업고객|C:일반기업고객|O:임시기업고객|P:임시개인고객|Q:일반개인고객|R:정규개인고객|S:우수개인고객', 
	CREATE_DATE 	TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP,
	CREATE_USER		VARCHAR(10) DEFAULT NULL,
	UPDATE_DATE 	TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_USER		VARCHAR(10) DEFAULT NULL,
	DELETE_DATE		TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP,
	DELETE_USER		VARCHAR(10) DEFAULT NULL
);

INSERT INTO CUSTOM_COMP_HISTORY VALUES ( DEFAULT, #{compDto.custom_id}, #{compDto.custom_kind_cd}, 'O', DEFAULT, #{compDto.custom_id}, NULL, NULL, NULL, NULL );

CREATE TABLE CUSTOM_PERSON_HISTORY( 
	SEQ				INT(15)		AUTO_INCREMENT UNIQUE KEY,
	CUSTOM_ID 		INT(8) 		NOT NULL PRIMARY KEY, 
	CUSTOM_KIND_CD	INT(3) 		NOT NULL COMMENT '1:기업고객|2:개인고객|101:유통|102:대형마트|103:중형마트|104:소형마트|105:편의점|201:공장|202:택배|203:우체국|301:컨테이너위탁업체|302:트랙카위탁업체|303:표준위탁업체|501:항공운송|502:선박운송|503:기차운송|505:표준차량운송|506:고속버스운송|507:개별차량운송|601:농업공급자|602:수산업공급자|603:축산업공급자', 
	CUSTOM_GRADE	VARCHAR(1) 	NOT NULL  COMMENT 'A:우수기업고객|B:정규기업고객|C:일반기업고객|O:임시기업고객|P:임시개인고객|Q:일반개인고객|R:정규개인고객|S:우수개인고객', 
	GENDER			INT(1)		NULL COMMENT 'M:남자|W:여자',
	CREATE_DATE 	TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP, 
	CREATE_USER		VARCHAR(10) DEFAULT NULL, 
	UPDATE_DATE 	TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_USER		VARCHAR(10) DEFAULT NULL,
	DELETE_DATE		TIMESTAMP 	NULL DEFAULT CURRENT_TIMESTAMP, 
	DELETE_USER		VARCHAR(10) DEFAULT NULL 
); 

INSERT INTO CUSTOM_PERSON_HISTORY VALUES ( DEFAULT, #{personDto.custom_id}, #{personDto.custom_kind_cd}, 'P', #{personDto.gender}, DEFAULT, #{compDto.custom_id}, NULL, NULL, NULL, NULL );

