drop table KAKAOADDRESS;
create table KAKAOADDRESS (
	CUSTOMID int(8) not null primary key,
	MAPADDRESS varchar(100) not null, -- KakaoMap검색용 도로명 주소(도로명 뒤 숫자 제외)
	LATITUDE double not null, -- 위도 
	LONGITUDE double not null, -- 경도
	KEY FK_KAKAOADDRESS_CUSTOMID (CUSTOMID),
	CONSTRAINT FK_KAKAOADDRESS_CUSTOMID FOREIGN KEY (CUSTOMID) REFERENCES CUSTOM_COMP (CUSTOM_ID) ON DELETE CASCADE ON UPDATE CASCADE 
);

desc KAKAOADDRESS;

select * from KAKAOADDRESS;

SELECT * FROM KAKAOADDRESS WHERE MAPADDRESS = '';